Repository ivanhr3/BeavArts, pull requests merged in 2021-04, with the labels that each got.

#62 Añadido atributo ID al modelo
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/static/resources/images/sadbeaver.png
  src/main/resources/static/resources/images/v2.png
  src/main/webapp/WEB-INF/jsp/exception.jsp
Labels: bug

#65 Finalizar Solicitudes y cambio Logo Menú
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/static/resources/images/v2.png
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
  src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Labels: bug, enhancement

#68 Arreglo de la función existsSolicitud
  src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
  src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
Labels: bug

#71 Arreglos a las vistas de solicitud y encargo
  src/main/java/org/springframework/samples/petclinic/model/Encargo.java
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/static/resources/images/favicon.png
  src/main/webapp/WEB-INF/jsp/encargos/createEncargosForm.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/aceptarSuccess.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/errorAceptar.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/errorRechazar.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/rechazarSuccess.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudExistente.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudPendiente.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudPropia.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudSinEncargo.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudSuccess.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesNotFound.jsp
  src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
  src/main/webapp/WEB-INF/tags/htmlHeader.tag
  src/main/webapp/WEB-INF/tags/inputNumberField.tag
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/model/EncargoValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/service/SolicitudServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Labels: bug, enhancement

#72 Eliminar Encargo
  src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
Labels: bug

#81 Info yml para Governify
  info.yml
Labels: enhancement

#94 Configuración Governify
  .travis.yml
  info.yml
Labels: enhancement

#103 Fixtestanuncios issue#102
  .travis.yml
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
Labels: bug

#108 Cambios valoracion issue#106
  .travis.yml
  src/main/java/org/springframework/samples/petclinic/model/Beaver.java
  src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
  src/main/java/org/springframework/samples/petclinic/repository/ValoracionRepository.java
  src/main/java/org/springframework/samples/petclinic/service/BeaverService.java
  src/main/java/org/springframework/samples/petclinic/service/ValoracionService.java
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/test/java/org/springframework/samples/petclinic/model/ValoracionValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
Labels: enhancement

#110 Refactorizacion general
  src/main/java/org/springframework/samples/petclinic/BeavartsApplication.java
  src/main/java/org/springframework/samples/petclinic/configuration/ExceptionHandlerConfiguration.java
  src/main/java/org/springframework/samples/petclinic/configuration/GenericIdToEntityConverter.java
  src/main/java/org/springframework/samples/petclinic/configuration/WebConfig.java
  src/main/java/org/springframework/samples/petclinic/model/Authorities.java
  src/main/java/org/springframework/samples/petclinic/model/Encargo.java
  src/main/java/org/springframework/samples/petclinic/model/Portfolio.java
  src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
  src/main/java/org/springframework/samples/petclinic/model/User.java
  src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
  src/main/java/org/springframework/samples/petclinic/repository/EncargoRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/PortFolioRepository.java
  src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
  src/main/java/org/springframework/samples/petclinic/service/BeaverService.java
  src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
  src/main/java/org/springframework/samples/petclinic/web/EncargoController.java
  src/main/resources/db/hsqldb/data.sql
  src/test/java/org/springframework/samples/petclinic/model/AnuncioValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/model/EncargoValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/model/SolicitudValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/model/ValoracionValidatorTests.java
  src/test/java/org/springframework/samples/petclinic/service/EncargoServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/CrashControllerTests.java
Labels: enhancement

#111 Crear valoracion issue#87
  .travis.yml
  src/main/java/org/springframework/samples/petclinic/model/Beaver.java
  src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
  src/main/java/org/springframework/samples/petclinic/repository/ValoracionRepository.java
  src/main/java/org/springframework/samples/petclinic/service/BeaverService.java
  src/main/java/org/springframework/samples/petclinic/service/ValoracionService.java
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/java/org/springframework/samples/petclinic/web/ValoracionController.java
  src/main/less/petclinic.scss
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/main/webapp/WEB-INF/jsp/valoracion/createValoracion.jsp
  src/main/webapp/WEB-INF/jsp/valoracion/lista.jsp
  src/test/java/org/springframework/samples/petclinic/service/ValoracionServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/ValoracionControllerTests.java
Labels: enhancement

#119 Funciones administrador issue#92
  src/main/java/org/springframework/samples/petclinic/repository/BeaverRepository.java
  src/main/java/org/springframework/samples/petclinic/service/BeaverService.java
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/java/org/springframework/samples/petclinic/web/EncargoController.java
  src/main/less/petclinic.scss
  src/main/resources/static/resources/images/search.svg
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
  src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/EncargoControllerTests.java
Labels: enhancement

#126 Añadidos mensajes de error en anuncios y eliminado boton de ban usuario cuando es admin.
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
  src/main/webapp/WEB-INF/jsp/encargos/listEncargos.jsp
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
Labels: bug

#129 Pasarela de pago issue#91
  pom.xml
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/repository/FacturaRepository.java
  src/main/java/org/springframework/samples/petclinic/service/FacturaService.java
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/creationFormAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Labels: enhancement

#133 Final sprint2 hotfix issue#132
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/less/petclinic.scss
  src/main/resources/static/resources/images/no-pictures.png
  src/main/resources/static/resources/images/search.png
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
Labels: bug

#135 Deploy Sprint 2 Issue #112
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/repository/FacturaRepository.java
  src/main/java/org/springframework/samples/petclinic/service/FacturaService.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/java/org/springframework/samples/petclinic/web/EncargoController.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/createAnunciosForm.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/facturas/facturasDetails.jsp
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/creationFormAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/EncargoControllerTests.java
Labels: bug, enhancement

#138 Cambio URL confirmación
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
Labels: bug

#144 Aumento del coverage issue#141
  src/test/java/org/springframework/samples/petclinic/service/AnuncioServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/BeaverServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/FacturaServiceTests.java
  src/test/java/org/springframework/samples/petclinic/service/SolicitudServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/AnuncioControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/BeaverControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/EncargoControllerTests.java
  src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Labels: enhancement

#145 Terminos y Condiciones
  src/main/java/org/springframework/samples/petclinic/configuration/SecurityConfiguration.java
  src/main/java/org/springframework/samples/petclinic/model/Anuncio.java
  src/main/java/org/springframework/samples/petclinic/model/Authorities.java
  src/main/java/org/springframework/samples/petclinic/model/Beaver.java
  src/main/java/org/springframework/samples/petclinic/model/Encargo.java
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/model/Portfolio.java
  src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
  src/main/java/org/springframework/samples/petclinic/model/User.java
  src/main/java/org/springframework/samples/petclinic/model/Valoracion.java
  src/main/java/org/springframework/samples/petclinic/repository/UserRepository.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/java/org/springframework/samples/petclinic/web/WelcomeController.java
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_de.properties
  src/main/resources/messages/messages_en.properties
  src/main/webapp/WEB-INF/jsp/terminos.jsp
  src/main/webapp/WEB-INF/jsp/users/confirmDeletion.jsp
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/main/webapp/WEB-INF/jsp/users/portability.jsp
  src/main/webapp/WEB-INF/jsp/users/succesfulDeletion.jsp
  src/main/webapp/WEB-INF/tags/footer.tag
  src/test/java/org/springframework/samples/petclinic/service/UserServiceTests.java
Labels: enhancement

#149 Hotfix en creacion de valoraciones
  src/main/java/org/springframework/samples/petclinic/service/ValoracionService.java
Labels: bug

#152 Bugfix registro issue#151
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
Labels: bug

#170 HOTFIX 02 - Redireccion al valorar a un usuario sin logearse issue#153
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Labels: invalid

#165 HOTFIX-05-Mensaje-al-pagar-issue#155
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/aceptarSuccess.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/rechazarSuccess.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
Labels: invalid

#171 HOTFIX 03 – Admin muestra un anuncio que ha creado el mismo issue#154
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
Labels: invalid

#173 Eliminadas relaciones con OrphanRemoval
  src/main/java/org/springframework/samples/petclinic/model/Anuncio.java
  src/main/java/org/springframework/samples/petclinic/model/Encargo.java
  src/main/java/org/springframework/samples/petclinic/model/User.java
Labels: bug

#174 Hotfix11pagos issue#162
  src/main/webapp/WEB-INF/jsp/solicitudes/creationForm.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
Labels: bug

#176 Creacion Doble eliminada
  src/main/java/org/springframework/samples/petclinic/service/AnuncioService.java
  src/main/java/org/springframework/samples/petclinic/service/EncargoService.java
Labels: bug

#178 Estado factura issue#168
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/web/FacturaController.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/webapp/WEB-INF/jsp/facturas/facturasDetails.jsp
  src/main/webapp/WEB-INF/jsp/facturas/listFacturas.jsp
  src/test/java/org/springframework/samples/petclinic/service/FacturaServiceTests.java
  src/test/java/org/springframework/samples/petclinic/web/FacturaControllerTests.java
Labels: enhancement

#180 Hotfix 09 - Al registrar no hay foto de perfil issue#158
  src/main/java/org/springframework/samples/petclinic/web/BeaverController.java
  src/main/less/petclinic.scss
  src/main/resources/static/resources/images/FotoBasePerfil.png
  src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/main/webapp/WEB-INF/jsp/valoracion/lista.jsp
Labels: bug

#179 Hotfix13borradoadmin issue#177
  src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
  src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/encargos/listEncargos.jsp
Labels: bug
