Repository ivanhr3/BeavArts, pull requests merged in 2021-05, with the labels that each got.

#163 HOTFIX-08 Revision de la vista de registro - issue#157
  src/main/java/org/springframework/samples/petclinic/model/Beaver.java
  src/main/java/org/springframework/samples/petclinic/web/AnuncioController.java
  src/main/less/petclinic.scss
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
  src/main/webapp/WEB-INF/tags/inputDNIField.tag
Labels: invalid

#185 Confirmacion de Recepcion de Encargo
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/web/SolicitudController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/facturas/facturasDetails.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
  src/test/java/org/springframework/samples/petclinic/web/SolicitudControllerTests.java
Labels: enhancement

#190 Logs acortados
  src/main/resources/application-mysql-travis.properties
  src/main/resources/application.properties
Labels: bug

#191 Facturaspersistence issue#188
  src/main/java/org/springframework/samples/petclinic/model/Factura.java
  src/main/java/org/springframework/samples/petclinic/model/Solicitud.java
  src/main/java/org/springframework/samples/petclinic/repository/SolicitudRepository.java
  src/main/java/org/springframework/samples/petclinic/service/FacturaService.java
  src/main/java/org/springframework/samples/petclinic/service/SolicitudService.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/resources/db/hsqldb/data.sql
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Labels: bug

#194 Cambios en vistas frontend issue#150
  src/main/less/petclinic.scss
  src/main/resources/static/resources/images/HomeFondo.png
  src/main/resources/static/resources/images/HomeFondo2.png
  src/main/resources/static/resources/images/HomeFondo3.png
  src/main/webapp/WEB-INF/jsp/accesoNoAutorizado.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/createAnunciosForm.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/encargos/createEncargosForm.jsp
  src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
  src/main/webapp/WEB-INF/jsp/encargos/listEncargos.jsp
  src/main/webapp/WEB-INF/jsp/exception.jsp
  src/main/webapp/WEB-INF/jsp/facturas/listFacturas.jsp
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/users/confirmDeletion.jsp
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
  src/main/webapp/WEB-INF/jsp/users/editarFotoPerfil.jsp
  src/main/webapp/WEB-INF/jsp/users/editarPortfolio.jsp
  src/main/webapp/WEB-INF/jsp/users/login-error.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
  src/main/webapp/WEB-INF/jsp/users/portability.jsp
  src/main/webapp/WEB-INF/jsp/users/succesfulDeletion.jsp
  src/main/webapp/WEB-INF/jsp/valoracion/createValoracion.jsp
  src/main/webapp/WEB-INF/jsp/valoracion/lista.jsp
  src/main/webapp/WEB-INF/jsp/welcome.jsp
Labels: enhancement

#200 Cambios en los términos y eliminar mensajes en inglés
  src/main/resources/messages/messages.properties
  src/main/resources/messages/messages_en.properties
Labels: bug

#202 Arreglado listado de solicitudes issue#201
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
Labels: invalid

#206 HOTFIX21 - Fix URL en listado de solicitudes issue #205
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
Labels: invalid

#210 Base datos remota issue#209
  Procfile
  src/main/resources/application-mysql.properties
Labels: enhancement

#212 Revert "Base datos remota issue#209"
  Procfile
  src/main/resources/application-mysql.properties
Labels: bug

#215 Changed Authorities dependencies
  src/main/java/org/springframework/samples/petclinic/service/AuthoritiesService.java
  src/main/java/org/springframework/samples/petclinic/service/UserService.java
Labels: bug

#226 Cambiado numero minimo caracteres de usuario
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
Labels: bug

#222 Hotfix 43 - Esconder Boton
  src/main/webapp/WEB-INF/jsp/encargos/createEncargosForm.jsp
Labels: bug

#223 Fix mantener datos en el form de registro cuando hay algun error
  src/main/java/org/springframework/samples/petclinic/web/UserController.java
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
Labels: bug

#231 Selección de especialidades más intuitivo
  src/main/webapp/WEB-INF/jsp/users/createBeaverForm.jsp
  src/main/webapp/WEB-INF/jsp/users/editarEspecialidades.jsp
Labels: bug

#235 Aplicar responsive a todas las vistas. mobile design issue#219
  src/main/less/petclinic.scss
  src/main/webapp/WEB-INF/jsp/anuncios/anunciosDetails.jsp
  src/main/webapp/WEB-INF/jsp/anuncios/listAnuncios.jsp
  src/main/webapp/WEB-INF/jsp/encargos/encargosDetails.jsp
  src/main/webapp/WEB-INF/jsp/publicaciones/misPublicaciones.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/listadoSolicitudes.jsp
  src/main/webapp/WEB-INF/jsp/solicitudes/solicitudesDetails.jsp
  src/main/webapp/WEB-INF/jsp/users/listBeavers.jsp
  src/main/webapp/WEB-INF/jsp/users/perfilBeaver.jsp
Labels: enhancement
